import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css";
import { useState } from "react";

const API_KEY = "5814f1a24ac44cbf8ef151602231602";

export default function Home() {
  const [city, setCity] = useState("");
  const [currentWeatherData, setCurrentWeatherData] = useState<any>({});
  const [forecast, setForecast] = useState([]);
  async function getWeather() {
    try {
      const serverResponse = await fetch(
        "http://api.weatherapi.com/v1/forecast.json?key=" +
          API_KEY +
          "&q=" +
          city +
          "&days=10&aqi=no&alerts=no"
      );
      const data = await serverResponse.json();
      if (data?.cod === "400") throw data;
      setCurrentWeatherData(data.current);
      setForecast(data.forecast.forecastday);
    } catch (err) {
      console.log(err);
    }
  }
  return (
    <>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <input onChange={(e) => setCity(e.target.value)}></input>
        <button onClick={() => getWeather()}>Get</button>
        {Object.keys(currentWeatherData).length !== 0 ? (
          <>
            <h1>Temp</h1>
            <h3>{currentWeatherData.temp_c}</h3>
            <h1>Wind Speed</h1>
            <h3>{currentWeatherData.wind_mph}</h3>
            <h1>Humidity</h1>
            <h3>{currentWeatherData.humidity}</h3>
            <h1>Pressure</h1>
            <h3>{currentWeatherData.pressure_mb}</h3>
          </>
        ) : null}
        {forecast.map((x, index) => (
          <div key={index}>
            <h2>On {x.date}</h2>
            <h3>Max Temp</h3>
            <p>{x.day.maxtemp_c}</p>
            <h3>Min Temp</h3>
            <p>{x.day.mintemp_c}</p>
            <h3>Sunrise Time</h3>
            <p>{x.astro.sunrise}</p>
            <h3>Sunset Time</h3>
            <p>{x.astro.sunset}</p>
          </div>
        ))}
      </div>
    </>
  );
}
